version: "3"
services:
  api:
    container_name: lights
    env_file:
      - .env
    build: .
    restart: unless-stopped
    networks:
      - backend
    expose:
      - "5000"
  nginx:
    image: nginx
    container_name: reverse
    restart: unless-stopped
    networks:
      - backend
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
networks:
  backend:
    driver: bridge
